apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: agg-sent-minutely
  namespace: datascience
spec:
  schedule: "* * * * *"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: agg-sent-minutely
            image: 455897087921.dkr.ecr.us-east-1.amazonaws.com/agg-sent-minutely:latest
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                memory: 4Gi
                cpu: 0.1
              limits:
                  memory: 16Gi
                  cpu: 1.0
          restartPolicy: OnFailure